//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace OsmSharp.Osm.Xml.v0_6
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class api
    {
        private version versionField;

        private area areaField;

        private tracepoints tracepointsField;

        private waynodes waynodesField;

        private changesets changesetsField;

        private timeout timeoutField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("timeout")]
        public timeout timeout
        {
            get
            {
                return this.timeoutField;
            }
            set
            {
                this.timeoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("changesets")]
        public changesets changesets
        {
            get
            {
                return this.changesetsField;
            }
            set
            {
                this.changesetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("waynodes")]
        public waynodes waynodes
        {
            get
            {
                return this.waynodesField;
            }
            set
            {
                this.waynodesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tracepoints")]
        public tracepoints tracepoints
        {
            get
            {
                return this.tracepointsField;
            }
            set
            {
                this.tracepointsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("version")]
        public version version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("area")]
        public area area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        public status status { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class timeout
    {
        private long secondsField;

        private bool secondsFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long seconds
        {
            get
            {
                return this.secondsField;
            }
            set
            {
                this.secondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondsSpecified
        {
            get
            {
                return this.secondsFieldSpecified;
            }
            set
            {
                this.secondsFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class changesets
    {
        private long maximum_elementsField;

        private bool maximum_elementsFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maximum_elements
        {
            get
            {
                return this.maximum_elementsField;
            }
            set
            {
                this.maximum_elementsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximum_elementsSpecified
        {
            get
            {
                return this.maximum_elementsFieldSpecified;
            }
            set
            {
                this.maximum_elementsFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class waynodes
    {
        private long maximumField;

        private bool maximumFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maximum
        {
            get
            {
                return this.maximumField;
            }
            set
            {
                this.maximumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSpecified
        {
            get
            {
                return this.maximumFieldSpecified;
            }
            set
            {
                this.maximumFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class tracepoints
    {
        private long per_pageField;

        private bool per_pageFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long per_page
        {
            get
            {
                return this.per_pageField;
            }
            set
            {
                this.per_pageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool per_pageSpecified
        {
            get
            {
                return this.per_pageFieldSpecified;
            }
            set
            {
                this.per_pageFieldSpecified = value;
            }
        }
    }


    /// <remarks/>
    public class area
    {
        private double maximumField;

        private bool maximumFieldSpecified;

        /// <remarks/>
        [XmlAttribute]
        public double maximum
        {
            get
            {
                return this.maximumField;
            }
            set
            {
                this.maximumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSpecified
        {
            get
            {
                return this.maximumFieldSpecified;
            }
            set
            {
                this.maximumFieldSpecified = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class version
    {
        private double minimumField;

        private bool minimumFieldSpecified;

        private double maximumField;

        private bool maximumFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double minimum
        {
            get
            {
                return this.minimumField;
            }
            set
            {
                this.minimumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minimumSpecified
        {
            get
            {
                return this.minimumFieldSpecified;
            }
            set
            {
                this.minimumFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double maximum
        {
            get
            {
                return this.maximumField;
            }
            set
            {
                this.maximumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSpecified
        {
            get
            {
                return this.maximumFieldSpecified;
            }
            set
            {
                this.maximumFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class osmChange
    {

        private create[] createField;

        private modify[] modifyField;

        private delete[] deleteField;

        private double versionField;

        private bool versionFieldSpecified;

        private string generatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("create")]
        public create[] create
        {
            get
            {
                return this.createField;
            }
            set
            {
                this.createField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modify")]
        public modify[] modify
        {
            get
            {
                return this.modifyField;
            }
            set
            {
                this.modifyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delete")]
        public delete[] delete
        {
            get
            {
                return this.deleteField;
            }
            set
            {
                this.deleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class create
    {

        private node[] nodeField;

        private way[] wayField;

        private relation[] relationField;

        private double versionField;

        private bool versionFieldSpecified;

        private string generatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public node[] node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("way")]
        public way[] way
        {
            get
            {
                return this.wayField;
            }
            set
            {
                this.wayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation")]
        public relation[] relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class node
    {

        private tag[] tagField;

        private long idField;

        private bool idFieldSpecified;

        private double latField;

        private bool latFieldSpecified;

        private double lonField;

        private bool lonFieldSpecified;

        private string userField;

        private long uidField;

        private bool uidFieldSpecified;

        private bool visibleField;

        private bool visibleFieldSpecified;

        private ulong versionField;

        private bool versionFieldSpecified;

        private long changesetField;

        private bool changesetFieldSpecified;

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tag")]
        public tag[] tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latSpecified
        {
            get
            {
                return this.latFieldSpecified;
            }
            set
            {
                this.latFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double lon
        {
            get
            {
                return this.lonField;
            }
            set
            {
                this.lonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lonSpecified
        {
            get
            {
                return this.lonFieldSpecified;
            }
            set
            {
                this.lonFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uidSpecified
        {
            get
            {
                return this.uidFieldSpecified;
            }
            set
            {
                this.uidFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibleSpecified
        {
            get
            {
                return this.visibleFieldSpecified;
            }
            set
            {
                this.visibleFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long changeset
        {
            get
            {
                return this.changesetField;
            }
            set
            {
                this.changesetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changesetSpecified
        {
            get
            {
                return this.changesetFieldSpecified;
            }
            set
            {
                this.changesetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class tag
    {

        private string kField;

        private string vField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string k
        {
            get
            {
                return this.kField;
            }
            set
            {
                this.kField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class way
    {

        private nd[] ndField;

        private tag[] tagField;

        private long idField;

        private bool idFieldSpecified;

        private string userField;

        private long uidField;

        private bool uidFieldSpecified;

        private bool visibleField;

        private bool visibleFieldSpecified;

        private ulong versionField;

        private bool versionFieldSpecified;

        private long changesetField;

        private bool changesetFieldSpecified;

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nd")]
        public nd[] nd
        {
            get
            {
                return this.ndField;
            }
            set
            {
                this.ndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tag")]
        public tag[] tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uidSpecified
        {
            get
            {
                return this.uidFieldSpecified;
            }
            set
            {
                this.uidFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibleSpecified
        {
            get
            {
                return this.visibleFieldSpecified;
            }
            set
            {
                this.visibleFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long changeset
        {
            get
            {
                return this.changesetField;
            }
            set
            {
                this.changesetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changesetSpecified
        {
            get
            {
                return this.changesetFieldSpecified;
            }
            set
            {
                this.changesetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class nd
    {

        private long refField;

        private bool refFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool refSpecified
        {
            get
            {
                return this.refFieldSpecified;
            }
            set
            {
                this.refFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class relation
    {

        private member[] memberField;

        private tag[] tagField;

        private long idField;

        private bool idFieldSpecified;

        private string userField;

        private long uidField;

        private bool uidFieldSpecified;

        private bool visibleField;

        private bool visibleFieldSpecified;

        private ulong versionField;

        private bool versionFieldSpecified;

        private long changesetField;

        private bool changesetFieldSpecified;

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("member")]
        public member[] member
        {
            get
            {
                return this.memberField;
            }
            set
            {
                this.memberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tag")]
        public tag[] tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uidSpecified
        {
            get
            {
                return this.uidFieldSpecified;
            }
            set
            {
                this.uidFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibleSpecified
        {
            get
            {
                return this.visibleFieldSpecified;
            }
            set
            {
                this.visibleFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long changeset
        {
            get
            {
                return this.changesetField;
            }
            set
            {
                this.changesetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changesetSpecified
        {
            get
            {
                return this.changesetFieldSpecified;
            }
            set
            {
                this.changesetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class member
    {

        private memberType typeField;

        private bool typeFieldSpecified;

        private long refField;

        private bool refFieldSpecified;

        private string roleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public memberType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool refSpecified
        {
            get
            {
                return this.refFieldSpecified;
            }
            set
            {
                this.refFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum memberType
    {

        /// <remarks/>
        node,

        /// <remarks/>
        way,

        /// <remarks/>
        relation,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class modify
    {

        private node[] nodeField;

        private way[] wayField;

        private relation[] relationField;

        private double versionField;

        private bool versionFieldSpecified;

        private string generatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public node[] node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("way")]
        public way[] way
        {
            get
            {
                return this.wayField;
            }
            set
            {
                this.wayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation")]
        public relation[] relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class delete
    {
        private node[] nodeField;

        private way[] wayField;

        private relation[] relationField;

        private double versionField;

        private bool versionFieldSpecified;

        private string generatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public node[] node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("way")]
        public way[] way
        {
            get
            {
                return this.wayField;
            }
            set
            {
                this.wayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation")]
        public relation[] relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class osm
    {
        private api apiField;

        private bounds boundsField;

        private bound boundField;

        private node[] nodeField;

        private way[] wayField;

        private relation[] relationField;

        private changeset[] changesetField;

        private double versionField;

        private bool versionFieldSpecified;

        private string generatorField;

        /// <summary>
        /// Creates a new xml serializer object.
        /// </summary>
        public osm()
        {
            this.versionField = ((double)(0.6F));
            this.generatorField = "OsmSharp";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("api")]
        public api api
        {
            get
            {
                return this.apiField;
            }
            set
            {
                this.apiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bounds")]
        public bounds bounds
        {
            get
            {
                return this.boundsField;
            }
            set
            {
                this.boundsField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bound")]
        public bound bound
        {
            get
            {
                return this.boundField;
            }
            set
            {
                this.boundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public node[] node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("way")]
        public way[] way
        {
            get
            {
                return this.wayField;
            }
            set
            {
                this.wayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation")]
        public relation[] relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("changeset")]
        public changeset[] changeset
        {
            get
            {
                return this.changesetField;
            }
            set
            {
                this.changesetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }

        /// <remarks/>
        public user user { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class bounds
    {

        private double minlatField;

        private bool minlatFieldSpecified;

        private double minlonField;

        private bool minlonFieldSpecified;

        private double maxlatField;

        private bool maxlatFieldSpecified;

        private double maxlonField;

        private bool maxlonFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double minlat
        {
            get
            {
                return this.minlatField;
            }
            set
            {
                this.minlatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minlatSpecified
        {
            get
            {
                return this.minlatFieldSpecified;
            }
            set
            {
                this.minlatFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double minlon
        {
            get
            {
                return this.minlonField;
            }
            set
            {
                this.minlonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minlonSpecified
        {
            get
            {
                return this.minlonFieldSpecified;
            }
            set
            {
                this.minlonFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double maxlat
        {
            get
            {
                return this.maxlatField;
            }
            set
            {
                this.maxlatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxlatSpecified
        {
            get
            {
                return this.maxlatFieldSpecified;
            }
            set
            {
                this.maxlatFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double maxlon
        {
            get
            {
                return this.maxlonField;
            }
            set
            {
                this.maxlonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxlonSpecified
        {
            get
            {
                return this.maxlonFieldSpecified;
            }
            set
            {
                this.maxlonFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class bound
    {
        private string boxField;

        private bool boxFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string box
        {
            get
            {
                return this.boxField;
            }
            set
            {
                this.boxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boxSpecified
        {
            get
            {
                return this.boxFieldSpecified;
            }
            set
            {
                this.boxFieldSpecified = value;
            }
        }

        private string originField;

        private bool originFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originSpecified
        {
            get
            {
                return this.originFieldSpecified;
            }
            set
            {
                this.originFieldSpecified = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    // [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    // [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class changeset
    {

        private tag[] tagField;

        private long idField;

        private bool idFieldSpecified;

        private string userField;

        private long uidField;

        private bool uidFieldSpecified;

        private System.DateTime created_atField;

        private bool created_atFieldSpecified;

        private System.DateTime closed_atField;

        private bool closed_atFieldSpecified;

        private bool openField;

        private bool openFieldSpecified;

        private double min_latField;

        private bool min_latFieldSpecified;

        private double min_lonField;

        private bool min_lonFieldSpecified;

        private double max_latField;

        private bool max_latFieldSpecified;

        private double max_lonField;

        private bool max_lonFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tag")]
        public tag[] tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uidSpecified
        {
            get
            {
                return this.uidFieldSpecified;
            }
            set
            {
                this.uidFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created_at
        {
            get
            {
                return this.created_atField;
            }
            set
            {
                this.created_atField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool created_atSpecified
        {
            get
            {
                return this.created_atFieldSpecified;
            }
            set
            {
                this.created_atFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime closed_at
        {
            get
            {
                return this.closed_atField;
            }
            set
            {
                this.closed_atField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool closed_atSpecified
        {
            get
            {
                return this.closed_atFieldSpecified;
            }
            set
            {
                this.closed_atFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool open
        {
            get
            {
                return this.openField;
            }
            set
            {
                this.openField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openSpecified
        {
            get
            {
                return this.openFieldSpecified;
            }
            set
            {
                this.openFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double min_lat
        {
            get
            {
                return this.min_latField;
            }
            set
            {
                this.min_latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool min_latSpecified
        {
            get
            {
                return this.min_latFieldSpecified;
            }
            set
            {
                this.min_latFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double min_lon
        {
            get
            {
                return this.min_lonField;
            }
            set
            {
                this.min_lonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool min_lonSpecified
        {
            get
            {
                return this.min_lonFieldSpecified;
            }
            set
            {
                this.min_lonFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double max_lat
        {
            get
            {
                return this.max_latField;
            }
            set
            {
                this.max_latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool max_latSpecified
        {
            get
            {
                return this.max_latFieldSpecified;
            }
            set
            {
                this.max_latFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double max_lon
        {
            get
            {
                return this.max_lonField;
            }
            set
            {
                this.max_lonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool max_lonSpecified
        {
            get
            {
                return this.max_lonFieldSpecified;
            }
            set
            {
                this.max_lonFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    public class status
    {
        /// <remarks/>
        [XmlAttribute]
        public string api { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public string database { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public string gpx { get; set; }
    }

    /// <remarks/>
    public class user
    {
        /// <remarks/>
        [XmlAttribute]
        public int id { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public string display_name { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public DateTime account_created { get; set; }
        /// <remarks/>
        public string description { get; set; }
        /// <remarks/>
        public img img { get; set; }
        /// <remarks/>
        [XmlElement("contributor-terms")]
        public contributorterms contributorterms { get; set; }
        /// <remarks/>
        public role[] roles { get; set; }
        /// <remarks/>
        public userchangeset changesets { get; set; }
        /// <remarks/>
        public traces traces { get; set; }
        /// <remarks/>
        public block[] blocks { get; set; }
    }

    /// <remarks/>
    public class block
    {
        /// <remarks/>
        [XmlAttribute]
        public int count { get; set; }
        /// <remarks/>
        [XmlAttribute]
        public int active { get; set; }
    }

    /// <remarks/>
    public class role
    {

    }

    /// <remarks/>
    public class userchangeset
    {
        /// <remarks/>
        [XmlAttribute]
        public int count { get; set; }
    }

    /// <remarks/>
    public class traces
    {
        /// <remarks/>
        [XmlAttribute]
        public int count { get; set; }
    }

    /// <remarks/>
    public class contributorterms
    {
        /// <remarks/>
        [XmlAttribute]
        public bool agreed { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public bool pd { get; set; }
    }

    /// <remarks/>
    public class img
    {
        /// <remarks/>
        [XmlAttribute]
        public string href { get; set; }
    }

    /// <remarks/>
    public class diffResult
    {
        /// <remarks/>
        [XmlAttribute]
        public string generator { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public double version { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified { get; set; }

    /// <remarks/>
    [XmlElement(Type = typeof(noderesult), ElementName = "node"),
         XmlElement(Type = typeof(wayresult), ElementName = "way"),
         XmlElement(Type = typeof(relationresult), ElementName = "relation")]
        public osmresult[] osmresult { get; set; } 
    }

    /// <remarks/>
    public abstract class osmresult
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long old_id { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool old_idSpecified { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long new_id { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool new_idSpecified { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int new_version { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool new_versionSpecified { get; set; }
    }

    /// <remarks/>
    public class noderesult : osmresult
    {

    }

    /// <remarks/>
    public class wayresult : osmresult
    {

    }

    /// <remarks/>
    public class relationresult : osmresult
    {

    }
}
