//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
using System.Xml;
using System.Xml.Linq;


namespace OsmSharp.IO.Xml.Gpx.v1_0
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.topografix.com/GPX/1/0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.topografix.com/GPX/1/0", IsNullable = false)]
    public partial class gpx
    {

        private string nameField;

        private string descField;

        private string authorField;

        private string emailField;

        private string urlField;

        private string urlnameField;

        private System.DateTime timeField;

        private bool timeFieldSpecified;

        private string keywordsField;

        private boundsType boundsField;

        private gpxWpt[] wptField;

        private gpxRte[] rteField;

        private gpxTrk[] trkField;

        private XElement[] anyField;

        private string versionField;

        private string creatorField;

        /// <remarks/>
        public gpx()
        {
            this.versionField = "1.0";
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        /// <remarks/>
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string urlname
        {
            get
            {
                return this.urlnameField;
            }
            set
            {
                this.urlnameField = value;
            }
        }

        /// <remarks/>
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string keywords
        {
            get
            {
                return this.keywordsField;
            }
            set
            {
                this.keywordsField = value;
            }
        }

        /// <remarks/>
        public boundsType bounds
        {
            get
            {
                return this.boundsField;
            }
            set
            {
                this.boundsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wpt")]
        public gpxWpt[] wpt
        {
            get
            {
                return this.wptField;
            }
            set
            {
                this.wptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rte")]
        public gpxRte[] rte
        {
            get
            {
                return this.rteField;
            }
            set
            {
                this.rteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trk")]
        public gpxTrk[] trk
        {
            get
            {
                return this.trkField;
            }
            set
            {
                this.trkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string creator
        {
            get
            {
                return this.creatorField;
            }
            set
            {
                this.creatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/0")]
    public partial class boundsType
    {

        private decimal minlatField;

        private decimal minlonField;

        private decimal maxlatField;

        private decimal maxlonField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal minlat
        {
            get
            {
                return this.minlatField;
            }
            set
            {
                this.minlatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal minlon
        {
            get
            {
                return this.minlonField;
            }
            set
            {
                this.minlonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxlat
        {
            get
            {
                return this.maxlatField;
            }
            set
            {
                this.maxlatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxlon
        {
            get
            {
                return this.maxlonField;
            }
            set
            {
                this.maxlonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.topografix.com/GPX/1/0")]
    public partial class gpxWpt
    {

        private decimal eleField;

        private bool eleFieldSpecified;

        private System.DateTime timeField;

        private bool timeFieldSpecified;

        private decimal magvarField;

        private bool magvarFieldSpecified;

        private decimal geoidheightField;

        private bool geoidheightFieldSpecified;

        private string nameField;

        private string cmtField;

        private string descField;

        private string srcField;

        private string urlField;

        private string urlnameField;

        private string symField;

        private string typeField;

        private fixType fixField;

        private bool fixFieldSpecified;

        private string satField;

        private decimal hdopField;

        private bool hdopFieldSpecified;

        private decimal vdopField;

        private bool vdopFieldSpecified;

        private decimal pdopField;

        private bool pdopFieldSpecified;

        private decimal ageofdgpsdataField;

        private bool ageofdgpsdataFieldSpecified;

        private string dgpsidField;

        private XElement[] anyField;

        private decimal latField;

        private decimal lonField;

        /// <remarks/>
        public decimal ele
        {
            get
            {
                return this.eleField;
            }
            set
            {
                this.eleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified
        {
            get
            {
                return this.eleFieldSpecified;
            }
            set
            {
                this.eleFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal magvar
        {
            get
            {
                return this.magvarField;
            }
            set
            {
                this.magvarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool magvarSpecified
        {
            get
            {
                return this.magvarFieldSpecified;
            }
            set
            {
                this.magvarFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal geoidheight
        {
            get
            {
                return this.geoidheightField;
            }
            set
            {
                this.geoidheightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geoidheightSpecified
        {
            get
            {
                return this.geoidheightFieldSpecified;
            }
            set
            {
                this.geoidheightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string cmt
        {
            get
            {
                return this.cmtField;
            }
            set
            {
                this.cmtField = value;
            }
        }

        /// <remarks/>
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        /// <remarks/>
        public string src
        {
            get
            {
                return this.srcField;
            }
            set
            {
                this.srcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string urlname
        {
            get
            {
                return this.urlnameField;
            }
            set
            {
                this.urlnameField = value;
            }
        }

        /// <remarks/>
        public string sym
        {
            get
            {
                return this.symField;
            }
            set
            {
                this.symField = value;
            }
        }

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public fixType fix
        {
            get
            {
                return this.fixField;
            }
            set
            {
                this.fixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixSpecified
        {
            get
            {
                return this.fixFieldSpecified;
            }
            set
            {
                this.fixFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string sat
        {
            get
            {
                return this.satField;
            }
            set
            {
                this.satField = value;
            }
        }

        /// <remarks/>
        public decimal hdop
        {
            get
            {
                return this.hdopField;
            }
            set
            {
                this.hdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdopSpecified
        {
            get
            {
                return this.hdopFieldSpecified;
            }
            set
            {
                this.hdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vdop
        {
            get
            {
                return this.vdopField;
            }
            set
            {
                this.vdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdopSpecified
        {
            get
            {
                return this.vdopFieldSpecified;
            }
            set
            {
                this.vdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdopSpecified
        {
            get
            {
                return this.pdopFieldSpecified;
            }
            set
            {
                this.pdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal ageofdgpsdata
        {
            get
            {
                return this.ageofdgpsdataField;
            }
            set
            {
                this.ageofdgpsdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageofdgpsdataSpecified
        {
            get
            {
                return this.ageofdgpsdataFieldSpecified;
            }
            set
            {
                this.ageofdgpsdataFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string dgpsid
        {
            get
            {
                return this.dgpsidField;
            }
            set
            {
                this.dgpsidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon
        {
            get
            {
                return this.lonField;
            }
            set
            {
                this.lonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.topografix.com/GPX/1/0")]
    public enum fixType
    {

        /// <remarks/>
        none,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2d")]
        Item2d,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3d")]
        Item3d,

        /// <remarks/>
        dgps,

        /// <remarks/>
        pps,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.topografix.com/GPX/1/0")]
    public partial class gpxRte
    {

        private string nameField;

        private string cmtField;

        private string descField;

        private string srcField;

        private string urlField;

        private string urlnameField;

        private string numberField;

        private XElement[] anyField;

        private gpxRteRtept[] rteptField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string cmt
        {
            get
            {
                return this.cmtField;
            }
            set
            {
                this.cmtField = value;
            }
        }

        /// <remarks/>
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        /// <remarks/>
        public string src
        {
            get
            {
                return this.srcField;
            }
            set
            {
                this.srcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string urlname
        {
            get
            {
                return this.urlnameField;
            }
            set
            {
                this.urlnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rtept")]
        public gpxRteRtept[] rtept
        {
            get
            {
                return this.rteptField;
            }
            set
            {
                this.rteptField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.topografix.com/GPX/1/0")]
    public partial class gpxRteRtept
    {

        private decimal eleField;

        private bool eleFieldSpecified;

        private System.DateTime timeField;

        private bool timeFieldSpecified;

        private decimal magvarField;

        private bool magvarFieldSpecified;

        private decimal geoidheightField;

        private bool geoidheightFieldSpecified;

        private string nameField;

        private string cmtField;

        private string descField;

        private string srcField;

        private string urlField;

        private string urlnameField;

        private string symField;

        private string typeField;

        private fixType fixField;

        private bool fixFieldSpecified;

        private string satField;

        private decimal hdopField;

        private bool hdopFieldSpecified;

        private decimal vdopField;

        private bool vdopFieldSpecified;

        private decimal pdopField;

        private bool pdopFieldSpecified;

        private decimal ageofdgpsdataField;

        private bool ageofdgpsdataFieldSpecified;

        private string dgpsidField;

        private XElement[] anyField;

        private decimal latField;

        private decimal lonField;

        /// <remarks/>
        public decimal ele
        {
            get
            {
                return this.eleField;
            }
            set
            {
                this.eleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified
        {
            get
            {
                return this.eleFieldSpecified;
            }
            set
            {
                this.eleFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal magvar
        {
            get
            {
                return this.magvarField;
            }
            set
            {
                this.magvarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool magvarSpecified
        {
            get
            {
                return this.magvarFieldSpecified;
            }
            set
            {
                this.magvarFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal geoidheight
        {
            get
            {
                return this.geoidheightField;
            }
            set
            {
                this.geoidheightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geoidheightSpecified
        {
            get
            {
                return this.geoidheightFieldSpecified;
            }
            set
            {
                this.geoidheightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string cmt
        {
            get
            {
                return this.cmtField;
            }
            set
            {
                this.cmtField = value;
            }
        }

        /// <remarks/>
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        /// <remarks/>
        public string src
        {
            get
            {
                return this.srcField;
            }
            set
            {
                this.srcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string urlname
        {
            get
            {
                return this.urlnameField;
            }
            set
            {
                this.urlnameField = value;
            }
        }

        /// <remarks/>
        public string sym
        {
            get
            {
                return this.symField;
            }
            set
            {
                this.symField = value;
            }
        }

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public fixType fix
        {
            get
            {
                return this.fixField;
            }
            set
            {
                this.fixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixSpecified
        {
            get
            {
                return this.fixFieldSpecified;
            }
            set
            {
                this.fixFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string sat
        {
            get
            {
                return this.satField;
            }
            set
            {
                this.satField = value;
            }
        }

        /// <remarks/>
        public decimal hdop
        {
            get
            {
                return this.hdopField;
            }
            set
            {
                this.hdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdopSpecified
        {
            get
            {
                return this.hdopFieldSpecified;
            }
            set
            {
                this.hdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vdop
        {
            get
            {
                return this.vdopField;
            }
            set
            {
                this.vdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdopSpecified
        {
            get
            {
                return this.vdopFieldSpecified;
            }
            set
            {
                this.vdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdopSpecified
        {
            get
            {
                return this.pdopFieldSpecified;
            }
            set
            {
                this.pdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal ageofdgpsdata
        {
            get
            {
                return this.ageofdgpsdataField;
            }
            set
            {
                this.ageofdgpsdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageofdgpsdataSpecified
        {
            get
            {
                return this.ageofdgpsdataFieldSpecified;
            }
            set
            {
                this.ageofdgpsdataFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string dgpsid
        {
            get
            {
                return this.dgpsidField;
            }
            set
            {
                this.dgpsidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon
        {
            get
            {
                return this.lonField;
            }
            set
            {
                this.lonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.topografix.com/GPX/1/0")]
    public partial class gpxTrk
    {

        private string nameField;

        private string cmtField;

        private string descField;

        private string srcField;

        private string urlField;

        private string urlnameField;

        private string numberField;

        private XElement[] anyField;

        private gpxTrkTrksegTrkpt[] trksegField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string cmt
        {
            get
            {
                return this.cmtField;
            }
            set
            {
                this.cmtField = value;
            }
        }

        /// <remarks/>
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        /// <remarks/>
        public string src
        {
            get
            {
                return this.srcField;
            }
            set
            {
                this.srcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string urlname
        {
            get
            {
                return this.urlnameField;
            }
            set
            {
                this.urlnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trkpt", typeof(gpxTrkTrksegTrkpt), IsNullable = false)]
        public gpxTrkTrksegTrkpt[] trkseg
        {
            get
            {
                return this.trksegField;
            }
            set
            {
                this.trksegField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.topografix.com/GPX/1/0")]
    public partial class gpxTrkTrksegTrkpt
    {

        private decimal eleField;

        private bool eleFieldSpecified;

        private System.DateTime timeField;

        private bool timeFieldSpecified;

        private decimal courseField;

        private bool courseFieldSpecified;

        private decimal speedField;

        private bool speedFieldSpecified;

        private decimal magvarField;

        private bool magvarFieldSpecified;

        private decimal geoidheightField;

        private bool geoidheightFieldSpecified;

        private string nameField;

        private string cmtField;

        private string descField;

        private string srcField;

        private string urlField;

        private string urlnameField;

        private string symField;

        private string typeField;

        private fixType fixField;

        private bool fixFieldSpecified;

        private string satField;

        private decimal hdopField;

        private bool hdopFieldSpecified;

        private decimal vdopField;

        private bool vdopFieldSpecified;

        private decimal pdopField;

        private bool pdopFieldSpecified;

        private decimal ageofdgpsdataField;

        private bool ageofdgpsdataFieldSpecified;

        private string dgpsidField;

        private XElement[] anyField;

        private decimal latField;

        private decimal lonField;

        /// <remarks/>
        public decimal ele
        {
            get
            {
                return this.eleField;
            }
            set
            {
                this.eleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified
        {
            get
            {
                return this.eleFieldSpecified;
            }
            set
            {
                this.eleFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal course
        {
            get
            {
                return this.courseField;
            }
            set
            {
                this.courseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool courseSpecified
        {
            get
            {
                return this.courseFieldSpecified;
            }
            set
            {
                this.courseFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool speedSpecified
        {
            get
            {
                return this.speedFieldSpecified;
            }
            set
            {
                this.speedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal magvar
        {
            get
            {
                return this.magvarField;
            }
            set
            {
                this.magvarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool magvarSpecified
        {
            get
            {
                return this.magvarFieldSpecified;
            }
            set
            {
                this.magvarFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal geoidheight
        {
            get
            {
                return this.geoidheightField;
            }
            set
            {
                this.geoidheightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geoidheightSpecified
        {
            get
            {
                return this.geoidheightFieldSpecified;
            }
            set
            {
                this.geoidheightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string cmt
        {
            get
            {
                return this.cmtField;
            }
            set
            {
                this.cmtField = value;
            }
        }

        /// <remarks/>
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        /// <remarks/>
        public string src
        {
            get
            {
                return this.srcField;
            }
            set
            {
                this.srcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string urlname
        {
            get
            {
                return this.urlnameField;
            }
            set
            {
                this.urlnameField = value;
            }
        }

        /// <remarks/>
        public string sym
        {
            get
            {
                return this.symField;
            }
            set
            {
                this.symField = value;
            }
        }

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public fixType fix
        {
            get
            {
                return this.fixField;
            }
            set
            {
                this.fixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixSpecified
        {
            get
            {
                return this.fixFieldSpecified;
            }
            set
            {
                this.fixFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string sat
        {
            get
            {
                return this.satField;
            }
            set
            {
                this.satField = value;
            }
        }

        /// <remarks/>
        public decimal hdop
        {
            get
            {
                return this.hdopField;
            }
            set
            {
                this.hdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdopSpecified
        {
            get
            {
                return this.hdopFieldSpecified;
            }
            set
            {
                this.hdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vdop
        {
            get
            {
                return this.vdopField;
            }
            set
            {
                this.vdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdopSpecified
        {
            get
            {
                return this.vdopFieldSpecified;
            }
            set
            {
                this.vdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal pdop
        {
            get
            {
                return this.pdopField;
            }
            set
            {
                this.pdopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdopSpecified
        {
            get
            {
                return this.pdopFieldSpecified;
            }
            set
            {
                this.pdopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal ageofdgpsdata
        {
            get
            {
                return this.ageofdgpsdataField;
            }
            set
            {
                this.ageofdgpsdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageofdgpsdataSpecified
        {
            get
            {
                return this.ageofdgpsdataFieldSpecified;
            }
            set
            {
                this.ageofdgpsdataFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string dgpsid
        {
            get
            {
                return this.dgpsidField;
            }
            set
            {
                this.dgpsidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon
        {
            get
            {
                return this.lonField;
            }
            set
            {
                this.lonField = value;
            }
        }
    }
}
