// OsmSharp - OpenStreetMap (OSM) SDK
// Copyright (C) 2013 Abelshausen Ben
// 
// This file is part of OsmSharp.
// 
// OsmSharp is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// OsmSharp is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with OsmSharp. If not, see <http://www.gnu.org/licenses/>.

namespace OsmSharp.Osm.PBF
{
    /// <summary>
    /// An object that implements this interface can consume objects generated by the PBFReader.
    /// </summary>
    internal interface IPBFPrimitiveBlockConsumer
    {
        /// <summary>
        /// Processes a primitive block of OSM data.
        /// </summary>
        /// <param name="block"></param>
        /// <param name="ignoreNodes"></param>
        /// <param name="ignoreWays"></param>
        /// <param name="ignoreRelations"></param>
        bool ProcessPrimitiveBlock(PrimitiveBlock block, bool ignoreNodes, bool ignoreWays, bool ignoreRelations);
    }
}