<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net462;net6.0;net8;net9</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<AssemblyName>OsmSharp.Test</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\OsmSharp\OsmSharp.csproj" />
		<ProjectReference Include="..\..\src\OsmSharp.Geo\OsmSharp.Geo.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="4.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NUnit" Version="3.13.3" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
		<PackageReference Include="NUnit.Analyzers" Version="3.3.0" />
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="data\pbf\*.pbf;data\xml\*.osm" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
	</ItemGroup>
</Project>